name: Upload changed files to dev OneLake
on:
#  push:
#    tags:
#      - v*
  workflow_dispatch:
jobs:
  deploy:
    permissions:
      contents: read
      actions: read
      id-token: write
    uses: ./.github/workflows/deploy.yml
    with:
      fabric_workspace: 'ldp-dev'
      env: dev
    secrets:
      azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
