name: Upload files to tst OneLake
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: tag to push to tst
jobs:
  deploy:
    permissions:
      contents: read
      actions: read
      id-token: write
    uses: ./.github/workflows/deploy.yml
    with:
      fabric_workspace: 'ldp-tst'
      env: tst
    secrets:
      azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
